### ISSUE TITLE
Backup doesn't work on my Mac (or with my data)

### ISSUE THREAD

**Issue by PaulineLawrey** [gaellafond/time-tracker#34]
Hi Gael
Thanks for writing this, it has made my life much easier.
The backup stopped working for me quite a few versions ago (sorry I didn't report it then).
Attached is the Console information from when I run it
[time-tracker-backup-error-message.log](https://github.com/gaellafond/time-tracker/files/7566523/time-tracker-backup-error-message.log)
Basically, nothing happens when I press the Backup button.
I'm using Chrome and I updated to the latest time-tracker.html version today.
I tried it on Firefox (with no data) and it seems to work.
I guess it is something to do with my data. Any ideas?
The Export to CSV works and I can send you my data if that helps.

**Comment by gaellafond** [comment]
Thanks for reporting the issue.
This is probably an issue with the quantity of data you have in the app. I though the solution I'm using was limited to 2GB. I will have to investigate further.

**Comment by gaellafond** [comment]
I found where the problem occurs. Thanks for the error log, that was very useful.

I pushed a hotfix. The backup button will works, but currupted items will be missing from the backup file. You should see an error window (alert) when such an item is found in the database.

Please, try the latest version. If you see an error window, copy its content in this issue (or screenshot) so I can fix this bug in a better way.

**Comment by PaulineLawrey** [comment]
![Time-tracker-bug-20211119](https://user-images.githubusercontent.com/22927881/142593735-f1c9b0fb-5fc7-4023-9e39-5a9b1fdaea4b.png)

**Comment by gaellafond** [comment]
Thanks.
Your local storage contains an element with a very strange value. That should not be there. The elements should look something like:
```
{ "key": "cat1", "name": "eAtlas", "order": 3 }
```

I suspect that element could have been added to the local storage by another application. If it's the case, I could simply filter what is saved when the backup is called.

I forgot to add the key to the error message. I need to see what the element's Key looks like, to know if it's a corrupted element of the TimeTracker or if it's an element that was added by another application. I modified to the TimeTracker error message to show the key. If you could re-run it, that would be helpful.

**Comment by PaulineLawrey** [comment]
![bug-v2](https://user-images.githubusercontent.com/22927881/142597474-e1e77417-cc10-480c-8a03-7f7626c2f91e.png)

**Comment by gaellafond** [comment]
Just as I though. The application "jwplayer" saved a value in the localstorage database.

Normally, applications are not interfering with other. The localstorage database is isolated to prevent one website to see or alter the localstorage content of another website. Unfortunately, the TimeTracker is running locally (on localhost), not from a website. It's not online. So everything running locally are considered as been part of the same "website" and can interfere with each other.

I have refactored how the TimeTracker load and backup its values. It should not be affected by values added by other applications.

Thanks for reporting this issue. I'm surprised it never showed up before.

**Comment by gaellafond** [comment]
The issue should be fixed in the latest release. If not, I will re-open the issue.

**Comment by PaulineLawrey** [comment]
Thanks Gael - no problems now
